const illnesses = [
  "Arthritis",
  "Hypertension",
  "Diabetes",
  "Coronary heart disease",
  "Osteoporosis",
  "Cancer",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Stroke",
  "Dementia",
  "Glaucoma",
  "High cholesterol",
  "Chronic Kidney Disease",
  "Gastroesophageal reflux disease (GERD)",
  "Prostate cancer",
  "Bronchitis",
  "Migraine",
  "Back pain",
  "Osteoarthritis",
  "Sinusitis",
  "Urinary incontinence",
  "Overactive bladder",
  "Irritable bowel syndrome (IBS)",
  "Varicose veins",
  "Peripheral artery disease (PAD)",
  "Restless leg syndrome (RLS)",
  "Macular degeneration",
  "Fibromyalgia",
  "Rheumatoid arthritis",
  "Asthma",
  "Thyroid disease",
  "Prostatitis",
  "Epilepsy",
  "BPH (enlarged prostate)",
  "Gastritis",
  "Bipolar disorder",
  "Deep vein thrombosis (DVT)",
  "Uterine fibroids",
  "Peptic ulcer disease",
  "Allergies",
  "Anxiety disorder",
  "Cerebral palsy",
  "Chronic pain",
  "Gout",
  "Hepatitis",
  "Herpes",
  "Influenza (Flu)",
  "Insomnia",
  "Multiple sclerosis (MS)",
  "Obesity",
  "Osteopenia",
  "Osteoporosis",
  "Parkinson's disease",
  "Shingles",
  "Tension headache",
  "Tinnitus",
  "Tuberculosis (TB)",
  "Ulcerative colitis",
  "Persistent cough",
  "Sore throat",
  "Runny nose",
  "Allergic rhinitis",
  "Hay fever",
  "Common cold",
  "Ear infection",
  "Stomach flu (gastroenteritis)",
  "Food poisoning",
  "Insect bites and stings",
  "Athlete's foot",
  "Jock itch",
  "Ringworm",
  "Yeast infection",
  "Pink eye (conjunctivitis)",
  "Head lice",
  "Skin rash",
  "Poison ivy, oak, or sumac",
  "Heat rash",
  "Motion sickness",
  "Morning sickness (nausea and vomiting during pregnancy)",
  "Menstrual cramps",
  "Menopause symptoms",
  "Premenstrual syndrome (PMS)",
  "Stress",
  "Anxiety",
  "Depression",
  "Insomnia",
  "Fatigue",
  "Muscle aches and pain",
  "Sprains and strains",
  "Back pain",
  "Neck pain",
  "Shoulder pain",
  "Knee pain",
  "Hip pain",
  "Ankle pain",
  "Bladder infections",
  "Vaginal yeast infections",
  "Vaginal itching",
  "Diarrhea",
  "Constipation",
  "Nausea",
  "Vomiting",
  "Indigestion (dyspepsia)",
  "Heartburn",
  "Gas (flatulence)",
  "Hemorrhoids",
  "Pinkeye (conjunctivitis)",
  "Swimmer's ear (otitis externa)",
  "Swollen glands",
  "Snoring",
  "Carpal tunnel syndrome",
  "Tennis elbow (epicondylitis)",
  "Golfer's elbow (medial epicondylitis)",
  "Bursitis",
  "Tendinitis",
  "Plantar fasciitis",
  "Sciatica",
  "Frozen shoulder",
  "Herniated disk",
  "Stress fractures",
  "Fibromyalgia",
  "Chronic fatigue syndrome",
  "Irritable bowel syndrome (IBS)",
  "Reflux (heartburn)",
  "Hiatal hernia",
  "Gallstones",
  "Ulcers",
  "Migraines",
  "Tension headaches",
  "Cluster headaches",
  "Sinus headaches",
  "Vertigo",
  "Tinnitus (ringing in the ears)",
  "Seasonal allergies",
  "Hives (urticaria)",
  "Eczema",
  "Psoriasis",
  "Acne",
  "Rosacea",
  "Dandruff (seborrheic dermatitis)",
  "Impetigo",
  "Shingles (herpes zoster)",
]

module.exports = illnesses
