const medications = [
  "Acetaminophen (Tylenol)",
  "Loratadine (Claritin)",
  "Cetirizine (Zyrtec)",
  "Fexofenadine (Allegra)",
  "Pseudoephedrine (Sudafed)",
  "Chlorpheniramine (Chlor-Trimeton)",
  "Montelukast (Singulair)",
  "Budesonide (Pulmicort)",
  "Salbutamol (Ventolin)",
  "Amoxicillin",
  "Ciprofloxacin (Cipro)",
  "Cefuroxime (Ceftin)",
  "Azithromycin (Zithromax)",
  "Ofloxacin (Floxin)",
  "Erythromycin",
  "Dextromethorphan (Robitussin)",
  "Guaifenesin (Mucinex)",
  "Cromolyn (Intal)",
  "Loperamide (Imodium)",
  "Bismuth subsalicylate (Pepto-Bismol)",
  "Metronidazole (Flagyl)",
  "Famotidine (Pepcid)",
  "Ranitidine (Zantac)",
  "Omeprazole (Prilosec)",
  "Lansoprazole (Prevacid)",
  "Dexamethasone",
  "Prednisone",
  "Hydrocodone (Vicodin)",
  "Oxycodone (OxyContin)",
  "Tramadol (Ultram)",
  "Methocarbamol (Robaxin)",
  "Carisoprodol (Soma)",
  "Cyclobenzaprine (Flexeril)",
  "Naproxen (Aleve)",
  "Meloxicam (Mobic)",
  "Celecoxib (Celebrex)",
  "Diclofenac (Voltaren)",
  "Indomethacin (Indocin)",
  "Ibuprofen (Advil)",
  "Acetaminophen (Tylenol)",
  "Metformin (Glucophage)",
  "Glyburide (Micronase)",
  "Metoprolol (Lopressor)",
  "Lisinopril (Prinivil)",
  "Amlodipine (Norvasc)",
  "Simvastatin (Zocor)",
  "Atorvastatin (Lipitor)",
  "Furosemide (Lasix)",
  "Spironolactone (Aldactone)",
  "Hydrochlorothiazide (HydroDIURIL)",
  "Captopril (Capoten)",
  "Enalapril (Vasotec)",
  "Warfarin (Coumadin)",
  "Aspirin",
  "Clopidogrel (Plavix)",
  "Dalteparin (Fragmin)",
  "Enoxaparin (Lovenox)",
  "Heparin",
  "Alendronate (Fosamax)",
  "Risedronate (Actonel)",
  "Ibandronate (Boniva)",
  "Zoledronic acid (Reclast)",
  "Calcium carbonate (Tums)",
  "Calcium citrate (Citracal)",
  "Vitamin D",
  "Methylphenidate (Ritalin)",
  "Dextroamphetamine (Dexedrine)",
  "Adderall",
  "Modafinil (Provigil)",
  "Armodafinil (Nuvigil)",
  "Phenobarbital",
  "Diazepam (Valium)",
  "Lorazepam (Ativan)",
  "Alprazolam (Xanax)",
  "Clonazepam (Klonopin)",
  "Sertraline (Zoloft)",
  "Fluoxetine (Prozac)",
  "Paroxetine (Paxil)",
  "Citalopram (Celexa)",
  "Escitalopram (Lexapro)",
  "Venlafaxine (Effexor)",
  "Bupropion (Wellbutrin)",
  "Nortriptyline (Pamelor)",
  "Amitriptyline (Elavil)",
  "Doxepin (Sinequan)",
  "Imipramine (Tofranil)",
  "Desipramine (Norpramin)",
  "Haloperidol (Haldol)",
  "Risperidone (Risperdal)",
  "Olanzapine (Zyprexa)",
  "Quetiapine (Seroquel)",
  "Aripiprazole (Abilify)",
];
